### ISSUE TITLE
Rql filter bug

### ISSUE THREAD

**Issue by victorynox** [rollun-com/rollun-js#1]
Когда делаешь фильтр в табличке, он неправильно генерирует rql ```
строку
```
&select(id,part_number,title,price,sku,location,state,description)eq(sku,14956391485925a46ca7f837 )&limit(10)
```
Нет символа `&` межу нодой select и нодами условий.
И лишний символ `&` перед нодой select

**Comment by bryakwork** [comment]
Fixed in 0.0.5
